# Generated by Django 4.2.17 on 2025-01-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article2',
            new_name='Article',
        ),
    ]
