# Generated by Django 4.2.17 on 2025-01-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_2_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_2',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article_2',
            name='text',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='Workshop Anecdote Text'),
        ),
        migrations.AlterField(
            model_name='article_2',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
