# Generated by Django 4.2.17 on 2025-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_2_author_alter_article_2_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_2',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Workshop Anecdote Text'),
        ),
    ]
