# Generated by Django 4.2.17 on 2025-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_2_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('article_image_description', models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='Image Description')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Author')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Workshop Anecdote Text')),
            ],
            options={
                'verbose_name_plural': 'Family Recollections',
            },
        ),
    ]
