# Generated by Django 5.1.5 on 2025-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_article_2_familyrecollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyrecollection',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Workshop Anecdote Text'),
        ),
        migrations.AlterField(
            model_name='workshopanecdote',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Workshop Anecdote Text'),
        ),
    ]
