# Generated by Django 5.1.5 on 2025-06-25 17:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_familyrecollection_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrecollection',
            name='text_intro',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Text'),
        ),
    ]
