# Generated by Django 5.1.5 on 2025-06-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_familyrecollection_text_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyrecollection',
            name='text_intro',
        ),
    ]
