from setuptools import setup, find_packages

setup(
    name='bealby_ploughs',  # Replace with your package name
    version='1.0.0',  # Initial version
    author='Murray Bealby',  # Your name
    author_email='bealbyploughs@gmail.com',  # Your email
    description='Bealby Ploughs',  # Short description
    long_description=open('README.md').read(),  # Read long description from README
    long_description_content_type='text/markdown',  # Format of the long description
    url='https://github.com/bealby/bealby_ploughs',  # URL to your project
    packages=find_packages(),  # Automatically find packages in the directory
    install_requires=[  # List of dependencies
        'numpy',
        'aniso8601',
        'asgiref',
        'astroid',
        'backports.entry-points-selectable',
        'boto3',
        'botocore',
        'certifi',
        'cffi',
        'charset-normalizer',
        'click',
        'cryptography',
        'defusedxml',
        'distlib',
        'dj-database-url',
        'Django',
        'django-allauth',
        'django-auto-logout',
        'django-cors-headers',
        'django-crispy-forms',
        'django-session-timeout',
        'django-storages',
        'docker',
        'env',
        'filelock',
        'Flask',
        'graphene',
        'graphene-django',
        'graphql-core',
        'graphql-relay',
        'gunicorn',
        'idna',
        'isort',
        'itsdangerous',
        'Jinja2',
        'jmespath',
        'joblib',
        'lazy-object-proxy',
        'MarkupSafe',
        'mccabe',
        'numpy',
        'oauthlib',
        'Pillow',
        'platformdirs',
        'promise',
        'psycopg2-binary',
        'pycodestyle',
        'pycparser',
        'pyflakes',
        'PyJWT',
        'pylint',
        'python-dateutil',
        'python3-openid',
        'pytz',
        'requests',
        'requests-oauthlib',
        'Rx',
        's3transfer',
        'scipy',
        'singledispatch',
        'six',
        'sqlparse',
        'text-unidecode',
        'threadpoolctl',
        'toml',
        'types-cryptography',
        'typing-extensions',
        'urllib3',
        'virtualenv',
        'websocket-client',
        'Werkzeug',
        'wrapt',
        'wheel',
        'setuptools',
    ],
    classifiers=[  # Classifiers for the package
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',  # Minimum Python version required
)