# Generated by Django 4.2.17 on 2025-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'Ploughs',
            },
        ),
    ]
