# Generated by Django 4.2.17 on 2025-01-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_1',
            name='image_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title'),
        ),
    ]
