# Generated by Django 5.1.5 on 2025-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_2_gallery_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='BealbyFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title')),
                ('image_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'Bealby Family',
            },
        ),
        migrations.DeleteModel(
            name='Gallery_1',
        ),
    ]
