# Generated by Django 5.1.5 on 2025-02-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_bealbyfamily_delete_gallery_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BealbyForestCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title')),
                ('image_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'Bealby Forest Cart',
            },
        ),
        migrations.CreateModel(
            name='BealbyPlough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title')),
                ('image_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'Bealby Ploughs',
            },
        ),
        migrations.CreateModel(
            name='BealbyWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title')),
                ('image_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'The Bealby Workshop',
            },
        ),
        migrations.CreateModel(
            name='BrookHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title')),
                ('image_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'Brook House',
            },
        ),
        migrations.CreateModel(
            name='WorkshopTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Image Title')),
                ('image_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Image Description')),
            ],
            options={
                'verbose_name_plural': 'Workshop Tools',
            },
        ),
        migrations.DeleteModel(
            name='Gallery_2',
        ),
        migrations.DeleteModel(
            name='Gallery_3',
        ),
    ]
