# Generated by Django 5.1.5 on 2025-03-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_bealbyfamily_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='bealbyforestcart',
            name='position',
            field=models.CharField(blank=True, help_text="Please add the letter 'h' for horizontal image and letter 'v' for vertical image", max_length=254, null=True, verbose_name='Horizontal or Verical Image?'),
        ),
        migrations.AddField(
            model_name='bealbyplough',
            name='position',
            field=models.CharField(blank=True, help_text="Please add the letter 'h' for horizontal image and letter 'v' for vertical image", max_length=254, null=True, verbose_name='Horizontal or Verical Image?'),
        ),
        migrations.AddField(
            model_name='bealbyworkshop',
            name='position',
            field=models.CharField(blank=True, help_text="Please add the letter 'h' for horizontal image and letter 'v' for vertical image", max_length=254, null=True, verbose_name='Horizontal or Verical Image?'),
        ),
        migrations.AddField(
            model_name='brookhouse',
            name='position',
            field=models.CharField(blank=True, help_text="Please add the letter 'h' for horizontal image and letter 'v' for vertical image", max_length=254, null=True, verbose_name='Horizontal or Verical Image?'),
        ),
        migrations.AddField(
            model_name='workshoptool',
            name='position',
            field=models.CharField(blank=True, help_text="Please add the letter 'h' for horizontal image and letter 'v' for vertical image", max_length=254, null=True, verbose_name='Horizontal or Verical Image?'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='position',
            field=models.CharField(blank=True, help_text="Please add the letter 'h' for horizontal image and letter 'v' for vertical image", max_length=254, null=True, verbose_name='Horizontal or Verical Image?'),
        ),
    ]
