# Generated by Django 5.1.5 on 2025-04-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_bealbyforestcart_position_bealbyplough_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoptool',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text'),
        ),
    ]
