# Generated by Django 5.1.5 on 2025-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_workshoptool_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bealbyforestcart',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='bealbyplough',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text'),
        ),
    ]
