# Generated by Django 5.1.5 on 2025-04-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_bealbyforestcart_text_bealbyplough_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bealbyforestcart',
            name='text',
        ),
        migrations.RemoveField(
            model_name='bealbyplough',
            name='text',
        ),
        migrations.RemoveField(
            model_name='workshoptool',
            name='text',
        ),
    ]
