# Generated by Django 4.2.17 on 2025-01-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name_plural': 'Home - About '},
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='text_1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='text_2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
