# Generated by Django 4.2.17 on 2025-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeabout_image_1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_1_description', models.CharField(blank=True, max_length=254, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2_description', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home - Articles',
            },
        ),
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name_plural': 'Home - About'},
        ),
    ]
