# Generated by Django 4.2.17 on 2025-01-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homearticles_alter_homeabout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticles',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homearticles',
            name='image_3_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
