# Generated by Django 4.2.17 on 2025-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_image_1_homearticles_article_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='paragraph_1',
            field=models.TextField(blank=True, help_text='This is the grey text', max_length=1000, null=True),
        ),
    ]
