# Generated by Django 4.2.17 on 2025-01-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homeabout_paragraph_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('research_image_1_description', models.CharField(blank=True, max_length=254, null=True)),
                ('research_title_1', models.CharField(blank=True, max_length=254, null=True)),
                ('research_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('research_image_2_description', models.CharField(blank=True, max_length=254, null=True)),
                ('research_title_2', models.CharField(blank=True, max_length=254, null=True)),
                ('research_image_3_description', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home - Research',
            },
        ),
    ]
