# Generated by Django 4.2.17 on 2025-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homeresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_image_1_description', models.CharField(blank=True, max_length=254, null=True)),
                ('gallery_title_1', models.CharField(blank=True, max_length=254, null=True)),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_image_2_description', models.CharField(blank=True, max_length=254, null=True)),
                ('gallery_title_2', models.CharField(blank=True, max_length=254, null=True)),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('gallery_image_3_description', models.CharField(blank=True, max_length=254, null=True)),
                ('gallery_title_3', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home - Gallery',
            },
        ),
        migrations.RenameField(
            model_name='homeresearch',
            old_name='_image_1',
            new_name='research_image_1',
        ),
        migrations.AddField(
            model_name='homeresearch',
            name='research_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homeresearch',
            name='research_title_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
