# Generated by Django 4.2.17 on 2025-01-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_image_1_homeabout_about_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeabout',
            old_name='about_image_1_description',
            new_name='about_image_1_title',
        ),
        migrations.RenameField(
            model_name='homeabout',
            old_name='about_image_2_description',
            new_name='about_image_2_title',
        ),
    ]
