# Generated by Django 4.2.17 on 2025-01-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_about_image_1_description_homeabout_about_image_1_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_1',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='(HOME) About - Image 1'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_1_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='(HOME) About - Image 1 Title'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_2',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='HOME) About - Image 2'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_2_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='(HOME) About - Image 2 Title'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='(HOME) About - Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='(HOME) About - Paragraph 2'),
        ),
    ]
