# Generated by Django 4.2.17 on 2025-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homeabout_about_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_1',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. About - Image'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_1_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. About - Image Title'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_2',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='2. About - Image '),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_image_2_title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. About - Image Title'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='1. About - Paragraph'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='2. About - Paragraph '),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_image_1',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. Article - Image'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_image_1_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Article - Image Description'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_image_2',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='2. Article - Image'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_image_2_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Article - Image Description'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_image_3',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Article - Image'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_image_3_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Article - Image Description'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_title_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Article - Title'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_title_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Article - Title'),
        ),
        migrations.AlterField(
            model_name='homearticles',
            name='article_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Article - Title'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_1',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_1_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Description'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_2',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_2_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Description'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_3_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Description'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Title'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Title'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Title'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_image_1',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_image_1_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Description'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_image_2',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='2. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_image_2_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Research - Image Description'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_image_3',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_image_3_description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Research - Image Description'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_title_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Image Title'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_title_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Research - Image title'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3.  Research - Image Title'),
        ),
    ]
