# Generated by Django 4.2.17 on 2025-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homeabout_about_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homearticles',
            name='article_image_1_description',
        ),
        migrations.RemoveField(
            model_name='homearticles',
            name='article_image_2_description',
        ),
        migrations.RemoveField(
            model_name='homearticles',
            name='article_image_3_description',
        ),
        migrations.AddField(
            model_name='homearticles',
            name='article_description_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Article - Description'),
        ),
        migrations.AddField(
            model_name='homearticles',
            name='article_description_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Article - Description'),
        ),
        migrations.AddField(
            model_name='homearticles',
            name='article_description_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Article - Description'),
        ),
    ]
