# Generated by Django 4.2.17 on 2025-01-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_homeresearch_research_image_1_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homegallery',
            name='gallery_image_1_description',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='gallery_image_2_description',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='gallery_image_3_description',
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_description_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Gallery - Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_description_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Research - Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_description_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Research - escription'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_alt_text_1',
            field=models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='1. Gallery - Image Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_alt_text_2',
            field=models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='2. Gallery - Image Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_alt_text_3',
            field=models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='3. Gallery - Image Description'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_1',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='1. Gallery - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_2',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='2. Gallery - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Research - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Gallery - Title'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Gallery - Title'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Research - Title'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_title_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Research - Title'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_title_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Research - Title'),
        ),
        migrations.AlterField(
            model_name='homeresearch',
            name='research_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3.  Research - Title'),
        ),
    ]
