# Generated by Django 4.2.17 on 2025-01-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_homegallery_gallery_image_1_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_description_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Gallery - Description'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_description_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Description'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Gallery - Image'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='gallery_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Title'),
        ),
    ]
