# Generated by Django 4.2.17 on 2025-01-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homegallery_gallery_description_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeabout',
            old_name='about_image_1_title',
            new_name='about_image_descritption_1',
        ),
        migrations.RenameField(
            model_name='homeabout',
            old_name='about_image_2_title',
            new_name='about_image_title_2',
        ),
        migrations.AddField(
            model_name='homeabout',
            name='about_image_descritption_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. About - Image Title'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='about_image_title_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='1. About - Image Title'),
        ),
    ]
