# Generated by Django 5.1.5 on 2025-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_homearticles_homearticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeabout',
            name='about_paragraph_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='3. About - Paragraph '),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='about_sub_title_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Title'),
        ),
    ]
