# Generated by Django 5.1.5 on 2025-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homeabout_about_paragraph_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeabout',
            name='about_sub_title_3',
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_3',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='3. About - Paragraph '),
        ),
    ]
