# Generated by Django 5.1.5 on 2025-04-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_homeabout_about_sub_title_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeabout',
            name='about_paragraph_4',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='4. About - Paragraph '),
        ),
    ]
