# Generated by Django 5.1.5 on 2025-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_homeabout_about_paragraph_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegallery',
            name='gallery_description_4',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_description_5',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_description_6',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_4',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Gallery - Image'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_5',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Gallery - Image'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_6',
            field=models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='3. Gallery - Image'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_alt_text_4',
            field=models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='3. Gallery - Image Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_alt_text_5',
            field=models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='3. Gallery - Image Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_image_alt_text_6',
            field=models.CharField(blank=True, help_text="'Alt' text required for image. Backend. Not seen on website", max_length=254, null=True, verbose_name='3. Gallery - Image Description'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_title_4',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Title'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_title_5',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Title'),
        ),
        migrations.AddField(
            model_name='homegallery',
            name='gallery_title_6',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='3. Gallery - Title'),
        ),
    ]
