# Generated by Django 5.1.5 on 2025-06-01 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_homegallery_gallery_description_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_2',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='2. About - Paragraph '),
        ),
    ]
