# Generated by Django 5.1.5 on 2025-06-01 19:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_homeabout_about_paragraph_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_2',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='2. About - Paragraph '),
        ),
    ]
