# Generated by Django 5.1.5 on 2025-06-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_homeabout_about_paragraph_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeabout',
            name='about_paragraph_3',
        ),
        migrations.RemoveField(
            model_name='homeabout',
            name='about_paragraph_4',
        ),
    ]
