# Generated by Django 5.1.5 on 2025-06-25 17:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_homeabout_about_paragraph_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='about_paragraph_1',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='1. About - Paragraph'),
        ),
    ]
