# Generated by Django 4.2.17 on 2025-01-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research_1',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='research_1',
            old_name='image_description',
            new_name='image_description_1',
        ),
        migrations.RenameField(
            model_name='research_1',
            old_name='image_title',
            new_name='image_title_1',
        ),
        migrations.RenameField(
            model_name='research_1',
            old_name='image_text',
            new_name='text',
        ),
    ]
