# Generated by Django 5.1.5 on 2025-04-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_bealbyfamily'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Research_2',
            new_name='BrookHouse',
        ),
        migrations.RenameModel(
            old_name='Research_1',
            new_name='InvoiceJournal',
        ),
    ]
