# Generated by Django 5.1.5 on 2025-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_rename_research_2_brookhouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bealbyfamily',
            name='authur',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Arthur'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='main_header',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Main Title'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='paragraph_1',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text_1'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='paragraph_2',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text_2'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='paragraph_3',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text_3'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='sub_header_1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sub Header 1'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='sub_header_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sub Header 1'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='sub_header_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sub Header 1'),
        ),
    ]
