# Generated by Django 5.1.5 on 2025-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_bealbyfamily_authur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bealbyfamily',
            name='paragraph_1',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text 1'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='paragraph_2',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text 2'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='paragraph_3',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text 3'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='sub_header_2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sub Header 2'),
        ),
        migrations.AlterField(
            model_name='bealbyfamily',
            name='sub_header_3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sub Header 3'),
        ),
    ]
