# Generated by Django 5.1.5 on 2025-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_alter_bealbyfamily_paragraph_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brookhouse',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Text'),
        ),
    ]
