# Generated by Django 5.1.5 on 2025-06-25 17:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_brookhouse_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brookhouse',
            name='text',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='invoicejournal',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
