# Generated by Django 5.1.5 on 2025-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_alter_brookhouse_text_alter_invoicejournal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicejournal',
            name='text_2',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='invoicejournal',
            name='text_3',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
