# Generated by Django 5.1.5 on 2025-07-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_invoicejournal_text_2_invoicejournal_text_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicejournal',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='invoicejournal',
            name='text_3',
        ),
    ]
