# Generated by Django 5.1.5 on 2025-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_remove_invoicejournal_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicejournal',
            name='text_2',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='invoicejournal',
            name='text_3',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
