# Generated by Django 5.1.5 on 2025-07-31 20:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_invoicejournal_text_2_invoicejournal_text_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicejournal',
            name='text',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='invoicejournal',
            name='text_2',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='invoicejournal',
            name='text_3',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Text'),
        ),
    ]
