# Generated by Django 5.1.5 on 2025-10-24 16:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_alter_invoicejournal_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bealby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Text')),
                ('image_1', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='Image')),
                ('image_title_1', models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Image Title')),
                ('image_description_1', models.CharField(blank=True, max_length=254, null=True, verbose_name='1. Image Description')),
                ('image_2', models.ImageField(blank=True, help_text='Please upload images 600x400. Max 300px', null=True, upload_to='', verbose_name='2. Image')),
                ('image_title_2', models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Image Title')),
                ('image_description_2', models.CharField(blank=True, max_length=254, null=True, verbose_name='2. Image Description')),
                ('text_2', tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Text')),
                ('text_3', tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name_plural': 'Bealby',
            },
        ),
    ]
